spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION} # a day
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION} # 7 days
    oauth2:
      client:
        registration:
          github:
            clientId: 4986e2ae73e22faff99d
            clientSecret: 2234a0d67f8ff08e71c2a5e9a400be411dd53712

application:
upload:
  directory: server/src/main/resources/static/uploads/
