name: Slack Notifications

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, closed]
  issues:
    types: [opened, closed]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Construct your Slack message here using GitHub event data
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, this is a notification from GitHub!"}' $SLACK_WEBHOOK_URL