name: Slack Notifications

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, closed]
  issues:
    types: [opened, closed]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, this is a notification from GitHub!"}' https://hooks.slack.com/services/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
          if [ $? -eq 0 ]; then
            echo "Notification sent successfully"
          else
            echo "Failed to send notification"
            echo "$response"  # Print response for debugging
            exit 1
          fi
